### PR TITLE
Fix typos in "server" word

### LINKED ISSUE #63: Potential typo ("sever" -> "server")
* [_**sever**_message_re](https://github.com/joshuaskelly/twitch-observer/blob/master/twitchobserver/twitchobserver.py#L69)
* [# Handle **sever** messages
](https://github.com/joshuaskelly/twitch-observer/blob/master/twitchobserver/twitchobserver.py#L514)
* [match = _**sever**_message_re.match(message)](https://github.com/joshuaskelly/twitch-observer/blob/master/twitchobserver/twitchobserver.py#L515)

All of these are typos, I guess.

### PR DESCRIPTION
**Pull request by Senpos**
Closes #63

### CODE REVIEW

**Comment by joshuaskelly** [comment]
👍 Looks good to me!

**Comment by PythooonUser** [comment]
Looks good!

Two things before merging tough:
- Please update version to `0.9.1` in the `__init__.py` file
- Add a new section in the `CHANGELOG.md` with a `Fixed` section

Thanks!

**Comment by Senpos** [comment]
@PythooonUser 
Sure, I can do that. 
Just curious: is it how you deal with versioning? Like, every PR is a new version?
I haven't worked with such schema before, almost all project I've seen are doing it a bit differently, like they accumulate PRs and then push a release with all of them bundled together with a big changelog.

**Comment by joshuaskelly** [comment]
We use Semantic Versioning
https://semver.org/

Technically we should only change the version when we publish. Since @PythooonUser already bumped the version number, you don't have to.

**Comment by joshuaskelly** [comment]
@Senpos I will wait for you to get your changes in and I'll publish the new version to PyPi.

**Comment by Senpos** [comment]
*I am not sure, was it a proper way to make changes to code, that was already edited, but I hope so, LOL*

**Pull request merged**
