### PR TITLE
Use long_description from README.md

### LINKED ISSUE #72: Use README.md in setup.py -> long_description
Isn't it a good idea to get rid of `long_description` and just load it from `README.md`, as described in [the official packaging tutorial](https://packaging.python.org/tutorials/packaging-projects/#creating-setup-py)?

It should be easier to make changes, since you will have to change only one file, rather than two. As I can see, both of them are (almost) identical.

```python
with open("README.md", "r") as fh:
    long_description = fh.read()

setuptools.setup(
    ...
    long_description=long_description,
    long_description_content_type="text/markdown",
    ...
```

That's all we need to change, I believe.

I can make a PR for this.

### PR DESCRIPTION
**Pull request by senpos**
Closes #72 

This change will make it easier to maintain `README` for both PyPI and repo, because actual text will come from a single place.

This idea comes from [the official packaging tutorial](https://packaging.python.org/tutorials/packaging-projects/#creating-setup-py).

Probably, nothing else should be done to make this work.

### CODE REVIEW

**Comment by joshuaskelly** [comment]
I noticed that the long description in `setup.py` doesn't include the Contributors section, but the README does. Will this render correctly on PyPi?

**Comment by Senpos** [comment]
@joshuaskelly 
I believe so.

Check out this [article](https://blog.thea.codes/github-flavored-markdown-on-pypi/), which claims that PyPI now supports GitHub-flavored Markdown since April 2018.
Also, here is a [discussion](https://github.com/pypa/packaging-problems/issues/126) about it.

**Comment by PythooonUser** [comment]
I wish Sphinx would support GFM, too...

**Comment by senpos** [comment]
@PythooonUser 
Have you ever seen GitBook? :)
They promise so many cool things ✨

**Comment by PythooonUser** [comment]
Oh, that looks nice!

**Review by joshuaskelly — APPROVED** [review]
Looks good! 👍

**Review by PythooonUser — APPROVED** [review]
Looks good. Feel free to merge at your earliest convenience.

**Pull request closed without merging**
